# This is a basic workflow to help you get started with Actions

name: Alice->Kamailio->Bob

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
#    branches: [ master ]
  pull_request:
#    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "20 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      MM_TYPE: kamailio
      MM_BRANCH: ${{ matrix.mm-branch }}
      RTPP_BRANCH: master
      RTPPC_TYPE: ${{ matrix.rtppc-type }}
      python-version: '3.10'
      PYTHON_CMD: "python3.10"

    strategy:
      matrix:
        mm-branch: ['master', '5.8', '5.7', '5.6', '5.5', '5.4', '5.3', '5.2', '5.1', '5.0', '4.4']
        rtppc-type: ['unix', 'udp', 'udp6']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.python-version }}

      - name: before_install
        run: sh -x cibits/before_install.sh

      - name: script
        run: sh -x ./test_run.sh

      - name: Test logs
        uses: actions/upload-artifact@v4
        with:
          name: test-logs_${{ matrix.mm-branch }}_${{ matrix.rtppc-type }}
          path: |
            kamailio.cfg
            bob.log
            alice.log
            rtpproxy.log
