name: Alice->SSUT->Bob

on:
  push:
  pull_request:
  release:
    types: [created]
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * 0"

jobs:
  # Alice->OpenSIPS->Bob
  opensips:
    name: OpenSIPS (${{ matrix.mm-branch }})
    uses: ./.github/workflows/.main.yml
    with:
      mm-type: 'opensips'
      mm-branch: ${{ matrix.mm-branch }}
      mm-auths: ${{ matrix.mm-auths }}
      rtppc-types: ${{ matrix.rtppc-types }}
      use-local-image: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
      artifact-files: 'opensips.cfg'
    strategy:
      fail-fast: false
      matrix:
        include:
          - mm-branch: 'master'
            mm-auths: '["", "passtr", "UAC", "UAS/auth", "UAS/auth_db/calculate_ha1", "UAS/auth_db/ha1"]'
            rtppc-types: '["unix", "udp", "udp6", "tcp", "tcp6"]'
          - mm-branch: '3.5'
            mm-auths: '[""]'
            rtppc-types: '["unix", "udp", "udp6", "tcp", "tcp6"]'
          - mm-branch: '3.4'
            mm-auths: '[""]'
            rtppc-types: '["unix", "udp", "udp6", "tcp", "tcp6"]'
          - mm-branch: '3.3'
            mm-auths: '[""]'
            rtppc-types: '["unix", "udp", "udp6", "tcp", "tcp6"]'
          - mm-branch: '3.2'
            mm-auths: '[""]'
            rtppc-types: '["unix", "udp", "udp6", "tcp", "tcp6"]'
          - mm-branch: '3.1'
            mm-auths: '[""]'
            rtppc-types: '["unix", "udp", "udp6"]'
          - mm-branch: '3.0'
            mm-auths: '[""]'
            rtppc-types: '["unix", "udp", "udp6"]'
          - mm-branch: '2.4'
            mm-auths: '[""]'
            rtppc-types: '["unix", "udp", "udp6"]'

  # Alice->Sippy Python B2B->Bob
  sippy_py_b2bua:
    name: Sippy Py-B2BUA (${{ matrix.mm-branch }})
    uses: ./.github/workflows/.main.yml
    with:
      mm-type: 'b2bua'
      mm-branch: ${{ matrix.mm-branch }}
      python-versions: '["3.9", "3.10", "3.11", "3.12", "3.13-dev"]'
      rtppc-types: '["unix", "cunix", "udp", "udp6", "tcp", "tcp6"]'
      use-local-image: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
      artifact-files: 'b2bua.log'
    strategy:
      fail-fast: false
      matrix:
        mm-branch: ['master', 'PRACK']

  # Alice->Sippy GO B2B->Bob
  sippy_go_b2bua:
    name: Sippy GO-B2BUA (${{ matrix.mm-branch }})
    uses: ./.github/workflows/.main.yml
    with:
      mm-type: 'go-b2bua'
      rtppc-types: '["unix", "cunix", "udp", "udp6", "tcp", "tcp6"]'
      use-local-image: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
      artifact-files: 'b2bua.log'

  # Alice->Kamailio->Bob
  kamailio:
    name: Kamailio (${{ matrix.mm-branch }})
    uses: ./.github/workflows/.main.yml
    with:
      mm-type: 'kamailio'
      mm-branch: ${{ matrix.mm-branch }}
      rtppc-types: '["unix", "udp", "udp6"]'
      use-local-image: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
      artifact-files: 'kamailio.cfg'
    strategy:
      fail-fast: false
      matrix:
        mm-branch: ['master', '6.0', '5.8', '5.7', '5.6', '5.5', '5.4', '5.3', '5.2', '5.1', '4.4']

  publish:
    needs: [opensips, sippy_py_b2bua, sippy_go_b2bua, kamailio]
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist
        twine upload dist/*
