# This is a basic workflow to help you get started with Actions

name: Alice->SSUT->Bob

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
#    branches: [ master ]
  pull_request:
#    branches: [ master ]

  release:
    types: [created]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "30 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # Alice->OpenSIPS->Bob
  opensips:
    uses: ./.github/workflows/.main.yml
    with:
      mm-type: 'opensips'
      mm-branch: ${{ matrix.mm-branch }}
      rtppc-type: ${{ matrix.rtppc-type }}
      artifact-files: 'opensips.cfg'
    strategy:
      matrix:
        mm-branch: ['master', '3.5', '3.4', '3.3', '3.2']
        rtppc-type: ['unix', 'udp', 'udp6', 'tcp', 'tcp6']
        include:
          - mm-branch: '2.4'
            rtppc-type: 'unix'
          - mm-branch: '2.4'
            rtppc-type: 'udp'
          - mm-branch: '2.4'
            rtppc-type: 'udp6'
          - mm-branch: '3.0'
            rtppc-type: 'unix'
          - mm-branch: '3.0'
            rtppc-type: 'udp'
          - mm-branch: '3.0'
            rtppc-type: 'udp6'
          - mm-branch: '3.1'
            rtppc-type: 'unix'
          - mm-branch: '3.1'
            rtppc-type: 'udp'
          - mm-branch: '3.1'
            rtppc-type: 'udp6'

  # Alice->OpenSIPS(RFC8760)->Bob
  opensips_rfc8760:
    uses: ./.github/workflows/.main.yml
    with:
      mm-type: 'opensips'
      mm-auth: ${{ matrix.mm-auth }}
      rtppc-type: ${{ matrix.rtppc-type }}
      artifact-files: 'opensips.cfg'

    strategy:
      matrix:
        rtppc-type: ['unix', 'udp', 'udp6', 'tcp', 'tcp6']
        mm-auth: ['passtr', 'UAC', 'UAS/auth', 'UAS/auth_db/calculate_ha1', 'UAS/auth_db/ha1']

  # Alice->Sippy Python B2B->Bob
  sippy_py_b2bua:
    uses: ./.github/workflows/.main.yml
    with:
      mm-type: 'b2bua'
      mm-branch: ${{ matrix.mm-branch }}
      rtppc-type: ${{ matrix.rtppc-type }}
      python-version: ${{ matrix.python-version }}
      artifact-files: 'b2bua.log'
    strategy:
      matrix:
        mm-branch: ['master', 'PRACK']
        rtppc-type: ['unix', 'cunix', 'udp', 'udp6', 'tcp', 'tcp6']
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13-dev']

  # Alice->Sippy GO B2B->Bob
  sippy_go_b2bua:
    uses: ./.github/workflows/.main.yml
    with:
      mm-type: 'go-b2bua'
      rtppc-type: ${{ matrix.rtppc-type }}
      artifact-files: 'b2bua.log'
    strategy:
      matrix:
        rtppc-type: ['unix', 'cunix', 'udp', 'udp6', 'tcp', 'tcp6']

  # Alice->Kamailio->Bob
  kamailio:
    uses: ./.github/workflows/.main.yml
    with:
      mm-type: 'kamailio'
      mm-branch: ${{ matrix.mm-branch }}
      rtppc-type: ${{ matrix.rtppc-type }}
      artifact-files: 'kamailio.cfg'
    strategy:
      matrix:
        mm-branch: ['master', '6.0', '5.8', '5.7', '5.6', '5.5', '5.4', '5.3', '5.2', '5.1', '4.4']
        rtppc-type: ['unix', 'udp', 'udp6']

  publish:
    needs: [opensips, opensips_rfc8760, sippy_py_b2bua, sippy_go_b2bua, kamailio]
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist
        twine upload dist/*
