name: Alice->SSUT->Bob

on:
  push:
  pull_request:
  release:
    types: [created]
  workflow_dispatch:
  schedule:
    - cron: "30 0 * * 0"

jobs:
  buildkit_image:
    name: Prepare BuildKit Image
    uses: sippy/cimagic/.github/workflows/GetCachedContainer.yml@v3
    with:
      image: moby/buildkit:buildx-stable-1
      cache-key-prefix: buildkit-image

  # Alice->OpenSIPS->Bob
  opensips:
    name: OpenSIPS (${{ matrix.mm-branch }})
    needs: buildkit_image
    uses: ./.github/workflows/.main.yml
    with:
      mm-type: 'opensips'
      mm-branch: ${{ matrix.mm-branch }}
      mm-auths: ${{ matrix.mm-auths }}
      rtppc-types: ${{ matrix.rtppc-types }}
      use-local-image: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
      artifact-files: 'opensips.cfg'
      buildkit-image: ${{ needs.buildkit_image.outputs.image }}
      buildkit-image-cache-key: ${{ needs.buildkit_image.outputs.image-cache-key }}
      buildkit-image-cache-path: ${{ needs.buildkit_image.outputs.image-cache-path }}
      buildkit-image-cache-tar: ${{ needs.buildkit_image.outputs.image-cache-tar }}
    strategy:
      fail-fast: false
      matrix:
        mm-branch: ['master', '4.0']
        mm-auths: ['["", "passtr", "UAC", "UAS/auth", "UAS/auth_db/calculate_ha1", "UAS/auth_db/ha1"]',]
        rtppc-types: ['["unix", "udp", "udp6", "tcp", "tcp6"]',]
        include:
          - mm-branch: '3.6'
            mm-auths: '[""]'
            rtppc-types: '["unix", "udp", "udp6", "tcp", "tcp6"]'
          - mm-branch: '3.5'
            mm-auths: '[""]'
            rtppc-types: '["unix", "udp", "udp6", "tcp", "tcp6"]'
          - mm-branch: '3.4'
            mm-auths: '[""]'
            rtppc-types: '["unix", "udp", "udp6", "tcp", "tcp6"]'
          - mm-branch: '3.3'
            mm-auths: '[""]'
            rtppc-types: '["unix", "udp", "udp6", "tcp", "tcp6"]'
          - mm-branch: '3.2'
            mm-auths: '[""]'
            rtppc-types: '["unix", "udp", "udp6", "tcp", "tcp6"]'
          - mm-branch: '3.1'
            mm-auths: '[""]'
            rtppc-types: '["unix", "udp", "udp6"]'
          - mm-branch: '3.0'
            mm-auths: '[""]'
            rtppc-types: '["unix", "udp", "udp6"]'

  # Alice->Sippy Python B2B->Bob
  sippy_py_b2bua:
    name: Sippy Py-B2BUA (${{ matrix.mm-branch }})
    needs: buildkit_image
    uses: ./.github/workflows/.main.yml
    with:
      mm-type: 'b2bua'
      mm-branch: ${{ matrix.mm-branch }}
      python-versions: '["3.10", "3.11", "3.12", "3.13", "3.14"]'
      rtppc-types: '["unix", "cunix", "udp", "udp6", "tcp", "tcp6"]'
      use-local-image: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
      artifact-files: 'b2bua.log'
      buildkit-image: ${{ needs.buildkit_image.outputs.image }}
      buildkit-image-cache-key: ${{ needs.buildkit_image.outputs.image-cache-key }}
      buildkit-image-cache-path: ${{ needs.buildkit_image.outputs.image-cache-path }}
      buildkit-image-cache-tar: ${{ needs.buildkit_image.outputs.image-cache-tar }}
    strategy:
      fail-fast: false
      matrix:
        mm-branch: ['master', 'wip', 'PRACK']

  # Alice->Sippy GO B2B->Bob
  sippy_go_b2bua:
    name: Sippy GO-B2BUA (${{ matrix.mm-branch }})
    needs: buildkit_image
    uses: ./.github/workflows/.main.yml
    with:
      mm-type: 'go-b2bua'
      mm-branch: ${{ matrix.mm-branch }}
      rtppc-types: '["unix", "cunix", "udp", "udp6", "tcp", "tcp6"]'
      use-local-image: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
      artifact-files: 'b2bua.log'
      buildkit-image: ${{ needs.buildkit_image.outputs.image }}
      buildkit-image-cache-key: ${{ needs.buildkit_image.outputs.image-cache-key }}
      buildkit-image-cache-path: ${{ needs.buildkit_image.outputs.image-cache-path }}
      buildkit-image-cache-tar: ${{ needs.buildkit_image.outputs.image-cache-tar }}
    strategy:
      fail-fast: false
      matrix:
        mm-branch: ['master']

  # Alice->Kamailio->Bob
  kamailio:
    name: Kamailio (${{ matrix.mm-branch }})
    needs: buildkit_image
    uses: ./.github/workflows/.main.yml
    with:
      mm-type: 'kamailio'
      mm-branch: ${{ matrix.mm-branch }}
      rtppc-types: '["unix", "udp", "udp6"]'
      use-local-image: ${{ github.event_name == 'pull_request' && github.event.pull_request.head.repo.fork }}
      artifact-files: 'kamailio.cfg'
      buildkit-image: ${{ needs.buildkit_image.outputs.image }}
      buildkit-image-cache-key: ${{ needs.buildkit_image.outputs.image-cache-key }}
      buildkit-image-cache-path: ${{ needs.buildkit_image.outputs.image-cache-path }}
      buildkit-image-cache-tar: ${{ needs.buildkit_image.outputs.image-cache-tar }}
    strategy:
      fail-fast: false
      matrix:
        mm-branch: ['master', '6.1', '6.0', '5.8', '5.7', '5.6', '5.5', '5.4', '5.3', '5.2', '5.1']

  publish:
    needs: [opensips, sippy_py_b2bua, sippy_go_b2bua, kamailio]
    if: github.event_name == 'release' && github.event.action == 'created'
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python
      uses: actions/setup-python@v6
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine
    - name: Build and publish
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python setup.py sdist
        twine upload dist/*
