# This is a basic workflow to help you get started with Actions

name: Alice->OpenSIPS->Bob

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ RFC8760 ]
  pull_request:
    branches: [ RFC8760 ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: "30 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    env:
      MM_TYPE: opensips
      MM_BRANCH: RFC8760
      MM_REPO: git://github.com/sippy/opensips.git
      MM_AUTH: ${{ matrix.mm-auth }}
      RTPP_BRANCH: master
      RTPPC_TYPE: ${{ matrix.rtppc-type }}
      python-version: '3.8'
      PYTHON_CMD: "python3.8"

    strategy:
      matrix:
        os: [ubuntu-20.04, ubuntu-18.04, ubuntu-16.04]
        rtppc-type: ['unix', 'udp', 'udp6', 'tcp', 'tcp6']
        mm-auth: ['passtr', 'UAC', 'UAS/auth', 'UAS/auth_db/calculate_ha1', 'UAS/auth_db/ha1']

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          ref: RFC8760

      - name: Set up Python ${{ env.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ env.python-version }}

      - name: before_install
        run: sh -x cibits/before_install.sh

      - name: script
        run: sh -x ./test_run.sh
